apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gravitee-apim-ui
  namespace: apim
spec:
  parentRefs:
    - name: main
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - apim.mattgerega.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /console
      backendRefs:
        - name: gravitee-apim-ui
          port: 8002
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gravitee-apim-portal
  namespace: apim
spec:
  parentRefs:
    - name: main
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - developer.mattgerega.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gravitee-apim-portal
          port: 8003
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gravitee-apim-api-management
  namespace: apim
spec:
  parentRefs:
    - name: main
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - apim.mattgerega.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /management
      backendRefs:
        - name: gravitee-apim-api
          port: 83
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gravitee-apim-api-portal
  namespace: apim
spec:
  parentRefs:
    - name: main
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - apim.mattgerega.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /portal
      backendRefs:
        - name: gravitee-apim-api
          port: 83
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gravitee-apim-gateway
  namespace: apim
spec:
  parentRefs:
    - name: main
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - apig.mattgerega.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gravitee-apim-gateway
          port: 82
